/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.DBConnect;
import Database.Data.Employee;
import Database.Data.TemplateFinger;
import EntityConstant.Constant;
import Helper.TKHelper;
import RestApi.Response.Fingerprint;
import RestApi.Response.Party;
import RestApi.ServiceGenerator;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import retrofit2.Call;
import retrofit2.Response;
import RestApi.Service.PartyService;

/**
 *
 * @author STN-COM-01
 */
public class Home extends javax.swing.JFrame {
    
    private int employeeID = -1;
    private ScanFinger scan;
    public String employeeNIK;
    private PartyService partyService;

    /**
     * Creates new form Employee
     */
    public Home() {
        initComponents();
        Initialize();
        setIconImage(Toolkit.getDefaultToolkit().getImage(Toolkit.getDefaultToolkit().getClass().getResource(TKHelper.ICON_PATH)));
    }
    
    private void Initialize() {
        partyService = ServiceGenerator.createBaseService(PartyService.class);
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
        
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
        
        setFieldDataTemplateFingerToHidden();
    }
    
    private void handleClosing() {
        int answer = showWarningMessage();
        if (answer == 0) {
            dispose();
            System.exit(0);
        }
    }
    
    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No", "Cancel"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;
        return JOptionPane.showOptionDialog(this, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icon, buttonLabels, defaultOption);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_employee_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLeftPinkyFinger = new java.awt.Button();
        btnLeftRingFinger = new java.awt.Button();
        btnLeftMiddleFinger = new java.awt.Button();
        btnLeftIndexFinger = new java.awt.Button();
        btnLeftThumbFinger = new java.awt.Button();
        btnRightThumbFinger = new java.awt.Button();
        btnRightIndexFinger = new java.awt.Button();
        btnRightMiddleFinger = new java.awt.Button();
        btnRightRingFinger = new java.awt.Button();
        btnRightPinkyFinger = new java.awt.Button();
        txt_employee_nik = new javax.swing.JTextField();
        finger1 = new javax.swing.JLabel();
        finger2 = new javax.swing.JLabel();
        finger3 = new javax.swing.JLabel();
        finger4 = new javax.swing.JLabel();
        finger5 = new javax.swing.JLabel();
        finger6 = new javax.swing.JLabel();
        finger7 = new javax.swing.JLabel();
        finger8 = new javax.swing.JLabel();
        finger9 = new javax.swing.JLabel();
        finger10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLeftPinkyFinger3 = new java.awt.Button();
        btnLeftPinkyFinger4 = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAboutProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Employee Finger - Home");
        setBackground(new java.awt.Color(32, 33, 35));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setText("NIK");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 51, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 104, 200, -1));

        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Nama Pegawai");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 51, -1, -1));

        txt_employee_name.setEditable(false);
        txt_employee_name.setBackground(new java.awt.Color(32, 33, 35));
        txt_employee_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_name.setBorder(null);
        txt_employee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_nameActionPerformed(evt);
            }
        });
        txt_employee_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employee_nameKeyPressed(evt);
            }
        });
        jPanel1.add(txt_employee_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 73, 200, 25));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 104, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right-hand.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-hand.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 167, -1, -1));

        btnLeftPinkyFinger.setBackground(java.awt.Color.red);
        btnLeftPinkyFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnLeftPinkyFinger.setLabel("1");
        btnLeftPinkyFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftPinkyFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftPinkyFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 192, -1, -1));

        btnLeftRingFinger.setActionCommand("2");
        btnLeftRingFinger.setBackground(java.awt.Color.red);
        btnLeftRingFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnLeftRingFinger.setLabel("2");
        btnLeftRingFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftRingFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftRingFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 144, -1, -1));

        btnLeftMiddleFinger.setBackground(java.awt.Color.red);
        btnLeftMiddleFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnLeftMiddleFinger.setLabel("3");
        btnLeftMiddleFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftMiddleFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftMiddleFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 144, -1, -1));

        btnLeftIndexFinger.setBackground(java.awt.Color.red);
        btnLeftIndexFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnLeftIndexFinger.setLabel("4");
        btnLeftIndexFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftIndexFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftIndexFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 144, -1, -1));

        btnLeftThumbFinger.setBackground(java.awt.Color.red);
        btnLeftThumbFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnLeftThumbFinger.setLabel("5");
        btnLeftThumbFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftThumbFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftThumbFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        btnRightThumbFinger.setBackground(java.awt.Color.red);
        btnRightThumbFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnRightThumbFinger.setLabel("6");
        btnRightThumbFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightThumbFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRightThumbFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 200, -1, -1));

        btnRightIndexFinger.setBackground(java.awt.Color.red);
        btnRightIndexFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnRightIndexFinger.setLabel("7");
        btnRightIndexFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightIndexFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRightIndexFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 130, -1, -1));

        btnRightMiddleFinger.setBackground(java.awt.Color.red);
        btnRightMiddleFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnRightMiddleFinger.setLabel("8");
        btnRightMiddleFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightMiddleFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRightMiddleFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 130, -1, -1));

        btnRightRingFinger.setBackground(java.awt.Color.red);
        btnRightRingFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnRightRingFinger.setLabel("9");
        btnRightRingFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightRingFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRightRingFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 130, -1, -1));

        btnRightPinkyFinger.setBackground(java.awt.Color.red);
        btnRightPinkyFinger.setForeground(new java.awt.Color(255, 255, 255));
        btnRightPinkyFinger.setLabel("10");
        btnRightPinkyFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightPinkyFingerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRightPinkyFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        txt_employee_nik.setBackground(new java.awt.Color(32, 33, 35));
        txt_employee_nik.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_nik.setBorder(null);
        txt_employee_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_nikActionPerformed(evt);
            }
        });
        txt_employee_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employee_nikKeyPressed(evt);
            }
        });
        jPanel1.add(txt_employee_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 73, 200, 25));
        jPanel1.add(finger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 268, -1, -1));
        jPanel1.add(finger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 274, -1, -1));
        jPanel1.add(finger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 280, -1, -1));
        jPanel1.add(finger4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 292, -1, -1));
        jPanel1.add(finger5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 304, -1, -1));
        jPanel1.add(finger6, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 260, -1, -1));
        jPanel1.add(finger7, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 266, -1, -1));
        jPanel1.add(finger8, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 272, -1, -1));
        jPanel1.add(finger9, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 278, -1, -1));
        jPanel1.add(finger10, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 341, -1, -1));

        jLabel5.setBackground(new java.awt.Color(187, 187, 187));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Unregister");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        btnLeftPinkyFinger3.setBackground(java.awt.Color.green);
        btnLeftPinkyFinger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftPinkyFinger3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftPinkyFinger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 13, 15));

        btnLeftPinkyFinger4.setBackground(java.awt.Color.red);
        btnLeftPinkyFinger4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftPinkyFinger4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeftPinkyFinger4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 13, 15));

        jLabel6.setBackground(new java.awt.Color(187, 187, 187));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registered");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jMenu1.setText("File");

        itemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        itemLogout.setText("Logout");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogout);

        itemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        itemExit.setText("Exit Program");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        itemAboutProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/version.png"))); // NOI18N
        itemAboutProgram.setText("About Program");
        itemAboutProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutProgramActionPerformed(evt);
            }
        });
        jMenu2.add(itemAboutProgram);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employee_nameActionPerformed

    private void txt_employee_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employee_nameKeyPressed

    }//GEN-LAST:event_txt_employee_nameKeyPressed

    private void txt_employee_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employee_nikActionPerformed

    private void txt_employee_nikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employee_nikKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String employeeNIK = txt_employee_nik.getText();
            this.employeeNIK = employeeNIK;
            if (!employeeNIK.isEmpty()) {
                resetDataTemplateFingerEmployee(true);
                fetchDataPartyByNIK(employeeNIK);
            } else {
                JOptionPane.showMessageDialog(this, "NIK Wajib Diisi.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_employee_nikKeyPressed

    private void btnLeftPinkyFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftPinkyFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger1.getText().isEmpty() ? Integer.parseInt(finger1.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 0, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftPinkyFingerActionPerformed

    private void btnLeftRingFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftRingFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger2.getText().isEmpty() ? Integer.parseInt(finger2.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 1, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftRingFingerActionPerformed

    private void btnLeftMiddleFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftMiddleFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger3.getText().isEmpty() ? Integer.parseInt(finger3.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 2, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftMiddleFingerActionPerformed

    private void btnLeftIndexFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftIndexFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger4.getText().isEmpty() ? Integer.parseInt(finger4.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 3, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftIndexFingerActionPerformed

    private void btnLeftThumbFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftThumbFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger5.getText().isEmpty() ? Integer.parseInt(finger5.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 4, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftThumbFingerActionPerformed

    private void btnRightThumbFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightThumbFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger6.getText().isEmpty() ? Integer.parseInt(finger6.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 5, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightThumbFingerActionPerformed

    private void btnRightIndexFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightIndexFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger7.getText().isEmpty() ? Integer.parseInt(finger7.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 6, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightIndexFingerActionPerformed

    private void btnRightMiddleFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightMiddleFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger8.getText().isEmpty() ? Integer.parseInt(finger8.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 7, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightMiddleFingerActionPerformed

    private void btnRightRingFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightRingFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger9.getText().isEmpty() ? Integer.parseInt(finger9.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 8, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightRingFingerActionPerformed

    private void btnRightPinkyFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightPinkyFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger10.getText().isEmpty() ? Integer.parseInt(finger10.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 9, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightPinkyFingerActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        handleClosing();
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        if (TKHelper.destroySession()) {
            SignIn signIn = new SignIn();
            this.dispose();
            signIn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Something's Wrong when clearing data session.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemAboutProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutProgramActionPerformed
        AboutProgram about = new AboutProgram();
        about.setVisible(true);
    }//GEN-LAST:event_itemAboutProgramActionPerformed

    private void btnLeftPinkyFinger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftPinkyFinger3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeftPinkyFinger3ActionPerformed

    private void btnLeftPinkyFinger4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftPinkyFinger4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeftPinkyFinger4ActionPerformed
    
    public void fetchDataPartyByNIK(String nik) {
        try {
            Call<Party> partyCall = partyService.apiSearchEmployeeByNik(nik);
            Response<Party> response = partyCall.execute();
            if (response.code() == 200) {
                Party party = response.body();
                txt_employee_name.setText(party.getFullName());
                this.employeeID = party.getId();
                if (!party.getFingerprints().isEmpty()) {
                    for (Fingerprint fingerprint : party.getFingerprints()) {
                        initDataTemplateFingerEmployee(fingerprint.getFingerType());
                        setDataTemplateFinger(fingerprint.getFingerType(), fingerprint.getTemplateFingerprintLength());
                    }
                } else {
                    resetDataTemplateFingerEmployee(false);
                }
            } else {
                JOptionPane.showMessageDialog(this, String.format("Pegawai dengan NIK = %s tidak ditemukan.", employeeNIK), "Warning", JOptionPane.WARNING_MESSAGE);
                reset();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
            reset();
        }
    }
    
    @Deprecated
    public void fetchDataEmployeeByNIK(String employeeNIK) {
        DBConnect db = new DBConnect();
        Employee employee = db.get_data_employee(employeeNIK);
        if (employee != null) {
            String employeeName = employee.getName();
            txt_employee_name.setText(employeeName);
            this.employeeID = employee.getId();
            List<TemplateFinger> dataTemplate = employee.getTemplate();
            if (!dataTemplate.isEmpty()) {
                for (TemplateFinger templateFinger : dataTemplate) {
                    int indexFinger = templateFinger.getIndex_finger();
                    int templateLength = templateFinger.getTemplate_length();
                    initDataTemplateFingerEmployee(indexFinger);
                    setDataTemplateFinger(indexFinger, templateLength);
                }
            } else {
                resetDataTemplateFingerEmployee(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pegawai dengan NIK = " + employeeNIK + " tidak ditemukan.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void initDataTemplateFingerEmployee(int indexFinger) {
        switch (indexFinger) {
            case 0:
                btnLeftPinkyFinger.setBackground(Color.GREEN);
                break;
            case 1:
                btnLeftRingFinger.setBackground(Color.GREEN);
                break;
            case 2:
                btnLeftMiddleFinger.setBackground(Color.GREEN);
                break;
            case 3:
                btnLeftIndexFinger.setBackground(Color.GREEN);
                break;
            case 4:
                btnLeftThumbFinger.setBackground(Color.GREEN);
                break;
            case 5:
                btnRightThumbFinger.setBackground(Color.GREEN);
                break;
            case 6:
                btnRightIndexFinger.setBackground(Color.GREEN);
                break;
            case 7:
                btnRightMiddleFinger.setBackground(Color.GREEN);
                break;
            case 8:
                btnRightRingFinger.setBackground(Color.GREEN);
                break;
            case 9:
                btnRightPinkyFinger.setBackground(Color.GREEN);
                break;
            default:
                break;
        }
    }
    
    private void resetDataTemplateFingerEmployee(boolean include_employeeID) {
        if (include_employeeID) {
            this.employeeID = -1;
        }
        Color reset = Color.RED;
        btnLeftPinkyFinger.setBackground(reset);
        btnLeftRingFinger.setBackground(reset);
        btnLeftMiddleFinger.setBackground(reset);
        btnLeftIndexFinger.setBackground(reset);
        btnLeftThumbFinger.setBackground(reset);
        btnRightThumbFinger.setBackground(reset);
        btnRightIndexFinger.setBackground(reset);
        btnRightMiddleFinger.setBackground(reset);
        btnRightRingFinger.setBackground(reset);
        btnRightPinkyFinger.setBackground(reset);
    }
    
    private void setFieldDataTemplateFingerToHidden() {
        finger1.setVisible(false);
        finger2.setVisible(false);
        finger3.setVisible(false);
        finger4.setVisible(false);
        finger5.setVisible(false);
        finger6.setVisible(false);
        finger7.setVisible(false);
        finger8.setVisible(false);
        finger9.setVisible(false);
        finger10.setVisible(false);
    }
    
    private void setDataTemplateFinger(int indexFinger, int templateLength) {
        switch (indexFinger) {
            case 0:
                finger1.setText(templateLength + "");
                break;
            case 1:
                finger2.setText(templateLength + "");
                break;
            case 2:
                finger3.setText(templateLength + "");
                break;
            case 3:
                finger4.setText(templateLength + "");
                break;
            case 4:
                finger5.setText(templateLength + "");
                break;
            case 5:
                finger6.setText(templateLength + "");
                break;
            case 6:
                finger7.setText(templateLength + "");
                break;
            case 7:
                finger8.setText(templateLength + "");
                break;
            case 8:
                finger9.setText(templateLength + "");
                break;
            case 9:
                finger10.setText(templateLength + "");
                break;
            default:
                break;
        }
    }
    
    private void reset() {
        resetDataTemplateFingerEmployee(true);
        txt_employee_nik.setText(Constant.EMPTY_STRING);
        txt_employee_name.setText(Constant.EMPTY_STRING);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLeftIndexFinger;
    private java.awt.Button btnLeftMiddleFinger;
    private java.awt.Button btnLeftPinkyFinger;
    private java.awt.Button btnLeftPinkyFinger3;
    private java.awt.Button btnLeftPinkyFinger4;
    private java.awt.Button btnLeftRingFinger;
    private java.awt.Button btnLeftThumbFinger;
    private java.awt.Button btnRightIndexFinger;
    private java.awt.Button btnRightMiddleFinger;
    private java.awt.Button btnRightPinkyFinger;
    private java.awt.Button btnRightRingFinger;
    private java.awt.Button btnRightThumbFinger;
    private javax.swing.JLabel finger1;
    private javax.swing.JLabel finger10;
    private javax.swing.JLabel finger2;
    private javax.swing.JLabel finger3;
    private javax.swing.JLabel finger4;
    private javax.swing.JLabel finger5;
    private javax.swing.JLabel finger6;
    private javax.swing.JLabel finger7;
    private javax.swing.JLabel finger8;
    private javax.swing.JLabel finger9;
    private javax.swing.JMenuItem itemAboutProgram;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txt_employee_name;
    private javax.swing.JTextField txt_employee_nik;
    // End of variables declaration//GEN-END:variables
}
