/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.DBConnect;
import Database.Data.Employee;
import Database.Data.TemplateFinger;
import Helper.TKHelper;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author STN-COM-01
 */
public class Home extends javax.swing.JFrame {

    private int employeeID = -1;
    private ScanFinger scan;
    public String employeeNIK;

    /**
     * Creates new form Employee
     */
    public Home() {
        initComponents();
        Initialize();
    }

    private void Initialize() {
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });

        setFieldDataTemplateFingerToHidden();
    }

    private void handleClosing() {
        int answer = showWarningMessage();
        if (answer == 0) {
            dispose();
            System.exit(0);
        }
    }

    private int showWarningMessage() {
        String[] buttonLabels = new String[]{"Yes", "No", "Cancel"};
        String defaultOption = buttonLabels[0];
        Icon icon = null;
        return JOptionPane.showOptionDialog(this, "Are you sure you want to exit?", "Warning", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icon, buttonLabels, defaultOption);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_employee_name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLeftPinkyFinger = new java.awt.Button();
        btnLeftRingFinger = new java.awt.Button();
        btnLeftMiddleFinger = new java.awt.Button();
        btnLeftIndexFinger = new java.awt.Button();
        btnLeftThumbFinger = new java.awt.Button();
        btnRightThumbFinger = new java.awt.Button();
        btnRightIndexFinger = new java.awt.Button();
        btnRightMiddleFinger = new java.awt.Button();
        btnRightRingFinger = new java.awt.Button();
        btnRightPinkyFinger = new java.awt.Button();
        txt_employee_nik = new javax.swing.JTextField();
        finger1 = new javax.swing.JLabel();
        finger2 = new javax.swing.JLabel();
        finger3 = new javax.swing.JLabel();
        finger4 = new javax.swing.JLabel();
        finger5 = new javax.swing.JLabel();
        finger6 = new javax.swing.JLabel();
        finger7 = new javax.swing.JLabel();
        finger8 = new javax.swing.JLabel();
        finger9 = new javax.swing.JLabel();
        finger10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAboutProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register Employee Finger - Home");
        setBackground(new java.awt.Color(32, 33, 35));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));

        jLabel1.setForeground(new java.awt.Color(57, 113, 177));
        jLabel1.setText("NIK");
        jLabel1.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(57, 113, 177));
        jLabel2.setText("Nama Pegawai");
        jLabel2.setToolTipText("");

        txt_employee_name.setEditable(false);
        txt_employee_name.setBackground(new java.awt.Color(32, 33, 35));
        txt_employee_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_name.setBorder(null);
        txt_employee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_nameActionPerformed(evt);
            }
        });
        txt_employee_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employee_nameKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/right-hand.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-hand.png"))); // NOI18N

        btnLeftPinkyFinger.setBackground(java.awt.Color.red);
        btnLeftPinkyFinger.setLabel("1");
        btnLeftPinkyFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftPinkyFingerActionPerformed(evt);
            }
        });

        btnLeftRingFinger.setActionCommand("2");
        btnLeftRingFinger.setBackground(java.awt.Color.red);
        btnLeftRingFinger.setLabel("2");
        btnLeftRingFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftRingFingerActionPerformed(evt);
            }
        });

        btnLeftMiddleFinger.setBackground(java.awt.Color.red);
        btnLeftMiddleFinger.setLabel("3");
        btnLeftMiddleFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftMiddleFingerActionPerformed(evt);
            }
        });

        btnLeftIndexFinger.setBackground(java.awt.Color.red);
        btnLeftIndexFinger.setLabel("4");
        btnLeftIndexFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftIndexFingerActionPerformed(evt);
            }
        });

        btnLeftThumbFinger.setBackground(java.awt.Color.red);
        btnLeftThumbFinger.setLabel("5");
        btnLeftThumbFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftThumbFingerActionPerformed(evt);
            }
        });

        btnRightThumbFinger.setBackground(java.awt.Color.red);
        btnRightThumbFinger.setLabel("6");
        btnRightThumbFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightThumbFingerActionPerformed(evt);
            }
        });

        btnRightIndexFinger.setBackground(java.awt.Color.red);
        btnRightIndexFinger.setLabel("7");
        btnRightIndexFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightIndexFingerActionPerformed(evt);
            }
        });

        btnRightMiddleFinger.setBackground(java.awt.Color.red);
        btnRightMiddleFinger.setLabel("8");
        btnRightMiddleFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightMiddleFingerActionPerformed(evt);
            }
        });

        btnRightRingFinger.setBackground(java.awt.Color.red);
        btnRightRingFinger.setLabel("9");
        btnRightRingFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightRingFingerActionPerformed(evt);
            }
        });

        btnRightPinkyFinger.setBackground(java.awt.Color.red);
        btnRightPinkyFinger.setLabel("10");
        btnRightPinkyFinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightPinkyFingerActionPerformed(evt);
            }
        });

        txt_employee_nik.setBackground(new java.awt.Color(32, 33, 35));
        txt_employee_nik.setForeground(new java.awt.Color(255, 255, 255));
        txt_employee_nik.setBorder(null);
        txt_employee_nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employee_nikActionPerformed(evt);
            }
        });
        txt_employee_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_employee_nikKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(txt_employee_nik)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(btnLeftRingFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnLeftMiddleFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnLeftIndexFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnLeftPinkyFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLeftThumbFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnRightThumbFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(finger1)
                                    .addComponent(finger2)
                                    .addComponent(finger3)
                                    .addComponent(finger4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnRightIndexFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnRightMiddleFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnRightRingFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRightPinkyFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 15, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(finger7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(finger6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(finger8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(finger9, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(finger5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finger10)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jLabel4)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_employee_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_employee_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLeftMiddleFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeftRingFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeftIndexFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnLeftPinkyFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(finger1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finger2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finger3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finger4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finger5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLeftThumbFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRightIndexFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRightMiddleFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRightRingFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btnRightThumbFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnRightPinkyFinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(finger6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(finger7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(finger8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(finger9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finger10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(167, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(61, 61, 61)))
        );

        jMenu1.setText("File");

        itemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        itemLogout.setText("Logout");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(itemLogout);

        itemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        itemExit.setText("Exit Program");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        itemAboutProgram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/version.png"))); // NOI18N
        itemAboutProgram.setText("About Program");
        itemAboutProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutProgramActionPerformed(evt);
            }
        });
        jMenu2.add(itemAboutProgram);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_employee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employee_nameActionPerformed

    private void txt_employee_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employee_nameKeyPressed

    }//GEN-LAST:event_txt_employee_nameKeyPressed

    private void txt_employee_nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_employee_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_employee_nikActionPerformed

    private void txt_employee_nikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_employee_nikKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String employeeNIK = txt_employee_nik.getText();
            this.employeeNIK = employeeNIK;
            if (!employeeNIK.isEmpty()) {
                resetDataTemplateFingerEmployee(true);
                fetchDataEmployeeByNIK(employeeNIK);
            } else {
                JOptionPane.showMessageDialog(this, "NIK Wajib Diisi.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_employee_nikKeyPressed

    private void btnLeftPinkyFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftPinkyFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger1.getText().isEmpty() ? Integer.parseInt(finger1.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 0, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftPinkyFingerActionPerformed

    private void btnLeftRingFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftRingFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger2.getText().isEmpty() ? Integer.parseInt(finger2.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 1, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftRingFingerActionPerformed

    private void btnLeftMiddleFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftMiddleFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger3.getText().isEmpty() ? Integer.parseInt(finger3.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 2, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftMiddleFingerActionPerformed

    private void btnLeftIndexFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftIndexFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger4.getText().isEmpty() ? Integer.parseInt(finger4.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 3, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftIndexFingerActionPerformed

    private void btnLeftThumbFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftThumbFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger5.getText().isEmpty() ? Integer.parseInt(finger5.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 4, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLeftThumbFingerActionPerformed

    private void btnRightThumbFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightThumbFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger6.getText().isEmpty() ? Integer.parseInt(finger6.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 5, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightThumbFingerActionPerformed

    private void btnRightIndexFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightIndexFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger7.getText().isEmpty() ? Integer.parseInt(finger7.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 6, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightIndexFingerActionPerformed

    private void btnRightMiddleFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightMiddleFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger8.getText().isEmpty() ? Integer.parseInt(finger8.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 7, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightMiddleFingerActionPerformed

    private void btnRightRingFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightRingFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger9.getText().isEmpty() ? Integer.parseInt(finger9.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 8, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightRingFingerActionPerformed

    private void btnRightPinkyFingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightPinkyFingerActionPerformed
        if (this.employeeID != -1) {
            int templateFinger = !finger10.getText().isEmpty() ? Integer.parseInt(finger10.getText()) : -1;
            scan = new ScanFinger(this.employeeID, 9, templateFinger, this);
            scan.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Employee ID.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRightPinkyFingerActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        handleClosing();
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        if (TKHelper.destroySession()) {
            SignIn signIn = new SignIn();
            this.dispose();
            signIn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Something's Wrong when clearing data session.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void itemAboutProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutProgramActionPerformed
        AboutProgram about = new AboutProgram();
        about.setVisible(true);
    }//GEN-LAST:event_itemAboutProgramActionPerformed

    public void fetchDataEmployeeByNIK(String employeeNIK) {
        DBConnect db = new DBConnect();
        Employee employee = db.get_data_employee(employeeNIK);
        if (employee != null) {
            String employeeName = employee.getName();
            txt_employee_name.setText(employeeName);
            this.employeeID = employee.getId();
            List<TemplateFinger> dataTemplate = employee.getTemplate();
            if (!dataTemplate.isEmpty()) {
                for (TemplateFinger templateFinger : dataTemplate) {
                    int indexFinger = templateFinger.getIndex_finger();
                    int templateLength = templateFinger.getTemplate_length();
                    initDataTemplateFingerEmployee(indexFinger);
                    setDataTemplateFinger(indexFinger, templateLength);
                }
            } else {
                resetDataTemplateFingerEmployee(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pegawai dengan NIK = " + employeeNIK + " tidak ditemukan.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void initDataTemplateFingerEmployee(int indexFinger) {
        switch (indexFinger) {
            case 0:
                btnLeftPinkyFinger.setBackground(Color.GREEN);
                break;
            case 1:
                btnLeftRingFinger.setBackground(Color.GREEN);
                break;
            case 2:
                btnLeftMiddleFinger.setBackground(Color.GREEN);
                break;
            case 3:
                btnLeftIndexFinger.setBackground(Color.GREEN);
                break;
            case 4:
                btnLeftThumbFinger.setBackground(Color.GREEN);
                break;
            case 5:
                btnRightThumbFinger.setBackground(Color.GREEN);
                break;
            case 6:
                btnRightIndexFinger.setBackground(Color.GREEN);
                break;
            case 7:
                btnRightMiddleFinger.setBackground(Color.GREEN);
                break;
            case 8:
                btnRightRingFinger.setBackground(Color.GREEN);
                break;
            case 9:
                btnRightPinkyFinger.setBackground(Color.GREEN);
                break;
            default:
                break;
        }
    }

    private void resetDataTemplateFingerEmployee(boolean include_employeeID) {
        if(include_employeeID) {
            this.employeeID = -1;
        }
        Color reset = Color.RED;
        btnLeftPinkyFinger.setBackground(reset);
        btnLeftRingFinger.setBackground(reset);
        btnLeftMiddleFinger.setBackground(reset);
        btnLeftIndexFinger.setBackground(reset);
        btnLeftThumbFinger.setBackground(reset);
        btnRightThumbFinger.setBackground(reset);
        btnRightIndexFinger.setBackground(reset);
        btnRightMiddleFinger.setBackground(reset);
        btnRightRingFinger.setBackground(reset);
        btnRightPinkyFinger.setBackground(reset);
    }

    private void setFieldDataTemplateFingerToHidden() {
        finger1.setVisible(false);
        finger2.setVisible(false);
        finger3.setVisible(false);
        finger4.setVisible(false);
        finger5.setVisible(false);
        finger6.setVisible(false);
        finger7.setVisible(false);
        finger8.setVisible(false);
        finger9.setVisible(false);
        finger10.setVisible(false);
    }

    private void setDataTemplateFinger(int indexFinger, int templateLength) {
        switch (indexFinger) {
            case 0:
                finger1.setText(templateLength + "");
                break;
            case 1:
                finger2.setText(templateLength + "");
                break;
            case 2:
                finger3.setText(templateLength + "");
                break;
            case 3:
                finger4.setText(templateLength + "");
                break;
            case 4:
                finger5.setText(templateLength + "");
                break;
            case 5:
                finger6.setText(templateLength + "");
                break;
            case 6:
                finger7.setText(templateLength + "");
                break;
            case 7:
                finger8.setText(templateLength + "");
                break;
            case 8:
                finger9.setText(templateLength + "");
                break;
            case 9:
                finger10.setText(templateLength + "");
                break;
            default:
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLeftIndexFinger;
    private java.awt.Button btnLeftMiddleFinger;
    private java.awt.Button btnLeftPinkyFinger;
    private java.awt.Button btnLeftRingFinger;
    private java.awt.Button btnLeftThumbFinger;
    private java.awt.Button btnRightIndexFinger;
    private java.awt.Button btnRightMiddleFinger;
    private java.awt.Button btnRightPinkyFinger;
    private java.awt.Button btnRightRingFinger;
    private java.awt.Button btnRightThumbFinger;
    private javax.swing.JLabel finger1;
    private javax.swing.JLabel finger10;
    private javax.swing.JLabel finger2;
    private javax.swing.JLabel finger3;
    private javax.swing.JLabel finger4;
    private javax.swing.JLabel finger5;
    private javax.swing.JLabel finger6;
    private javax.swing.JLabel finger7;
    private javax.swing.JLabel finger8;
    private javax.swing.JLabel finger9;
    private javax.swing.JMenuItem itemAboutProgram;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txt_employee_name;
    private javax.swing.JTextField txt_employee_nik;
    // End of variables declaration//GEN-END:variables
}
